// <auto-generated />
using System;
using System.Collections.Generic;
using BuyGuardian.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace BuyGuardian.Api.Migrations
{
    [DbContext(typeof(BuyGuardianContext))]
    [Migration("20260427004514_UpdateSellerMetadata")]
    partial class UpdateSellerMetadata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BuyGuardian.Api.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ExtractSchema")
                        .HasColumnType("jsonb");

                    b.Property<string>("LlmPromptTemplate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("BuyGuardian.Api.Models.Listing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Dictionary<string, object>>("RawMetadata")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("ScrapedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("TrustScore")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.HasIndex("ProductId");

                    b.HasIndex("SellerId");

                    b.ToTable("Listings");
                });

            modelBuilder.Entity("BuyGuardian.Api.Models.PriceHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ListingId");

                    b.ToTable("PriceHistories");
                });

            modelBuilder.Entity("BuyGuardian.Api.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Dictionary<string, object>>("Attributes")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<decimal>("AvgPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("CanonicalName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ListingsCount")
                        .HasColumnType("integer");

                    b.Property<Vector>("ProductVector")
                        .HasColumnType("vector(768)");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalName");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CategoryName");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("BuyGuardian.Api.Models.SearchQuery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AvgPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastScrape")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ListingsCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NextScrape")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("PriorityScore")
                        .HasColumnType("double precision");

                    b.Property<string>("QueryTerm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("VelocityScore")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("QueryTerm")
                        .IsUnique();

                    b.ToTable("SearchQueries");
                });

            modelBuilder.Entity("BuyGuardian.Api.Models.Seller", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccountAgeMonths")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAddressVerified")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPhoneVerified")
                        .HasColumnType("boolean");

                    b.Property<int>("NegativeFeedback")
                        .HasColumnType("integer");

                    b.Property<int>("NeutralFeedback")
                        .HasColumnType("integer");

                    b.Property<string>("OlxId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PositiveFeedback")
                        .HasColumnType("integer");

                    b.Property<int>("SuccessfulDeliveries")
                        .HasColumnType("integer");

                    b.Property<double>("TrustScore")
                        .HasColumnType("double precision");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OlxId")
                        .IsUnique();

                    b.ToTable("Sellers");
                });

            modelBuilder.Entity("BuyGuardian.Api.Models.Listing", b =>
                {
                    b.HasOne("BuyGuardian.Api.Models.Product", "Product")
                        .WithMany("Listings")
                        .HasForeignKey("ProductId");

                    b.HasOne("BuyGuardian.Api.Models.Seller", "Seller")
                        .WithMany("Listings")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("BuyGuardian.Api.Models.PriceHistory", b =>
                {
                    b.HasOne("BuyGuardian.Api.Models.Listing", "Listing")
                        .WithMany("PriceHistories")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("BuyGuardian.Api.Models.Product", b =>
                {
                    b.HasOne("BuyGuardian.Api.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BuyGuardian.Api.Models.Listing", b =>
                {
                    b.Navigation("PriceHistories");
                });

            modelBuilder.Entity("BuyGuardian.Api.Models.Product", b =>
                {
                    b.Navigation("Listings");
                });

            modelBuilder.Entity("BuyGuardian.Api.Models.Seller", b =>
                {
                    b.Navigation("Listings");
                });
#pragma warning restore 612, 618
        }
    }
}
